on: 
  push:
    branches: 
      - master
name: Publish Chatbot to Cpanel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        ftp-server: ${{ secrets.FTP_SERVER_CERTIFICATE }}
        ftp-username: ${{ secrets.FTP_USERNAME_CERTIFICATE }}
        ftp-password: ${{ secrets.FTP_PASSWORD_CERTIFICATE }}
